# Lab | Web Scraping

Welcome to the "Books to Scrape" Web Scraping Adventure Lab!

**Objective**

In this lab, we will embark on a mission to unearth valuable insights from the data available on Books to Scrape, an online platform showcasing a wide variety of books. As data analyst, you have been tasked with scraping a specific subset of book data from Books to Scrape to assist publishing companies in understanding the landscape of highly-rated books across different genres. Your insights will help shape future book marketing strategies and publishing decisions.

**Background**

In a world where data has become the new currency, businesses are leveraging big data to make informed decisions that drive success and profitability. The publishing industry, much like others, utilizes data analytics to understand market trends, reader preferences, and the performance of books based on factors such as genre, author, and ratings. Books to Scrape serves as a rich source of such data, offering detailed information about a diverse range of books, making it an ideal platform for extracting insights to aid in informed decision-making within the literary world.

**Task**

Your task is to create a Python script using BeautifulSoup and pandas to scrape Books to Scrape book data, focusing on book ratings and genres. The script should be able to filter books with ratings above a certain threshold and in specific genres. Additionally, the script should structure the scraped data in a tabular format using pandas for further analysis.

**Expected Outcome**

A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`. The function should scrape book data from the "Books to Scrape" website and return a `pandas` DataFrame with the following columns:

**Expected Outcome**

- A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`.
- The function should return a DataFrame with the following columns:
  - **UPC**: The Universal Product Code (UPC) of the book.
  - **Title**: The title of the book.
  - **Price (£)**: The price of the book in pounds.
  - **Rating**: The rating of the book (1-5 stars).
  - **Genre**: The genre of the book.
  - **Availability**: Whether the book is in stock or not.
  - **Description**: A brief description or product description of the book (if available).
  
You will execute this script to scrape data for books with a minimum rating of `4.0 and above` and a maximum price of `£20`. 

Remember to experiment with different ratings and prices to ensure your code is versatile and can handle various searches effectively!

**Resources**

- [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/index.html)
- [Books to Scrape](https://books.toscrape.com/)

**Hint**

Your first mission is to familiarize yourself with the **Books to Scrape** website. Navigate to [Books to Scrape](http://books.toscrape.com/) and explore the available books to understand their layout and structure. 

Next, think about how you can set parameters for your data extraction:

- **Minimum Rating**: Focus on books with a rating of 4.0 and above.
- **Maximum Price**: Filter for books priced up to £20.

After reviewing the site, you can construct a plan for scraping relevant data. Pay attention to the details displayed for each book, including the title, price, rating, and availability. This will help you identify the correct HTML elements to target with your scraping script.

Make sure to build your scraping URL and logic based on the patterns you observe in the HTML structure of the book listings!


---

**Best of luck! Immerse yourself in the world of books, and may the data be with you!**

**Important Note**:

In the fast-changing online world, websites often update and change their structures. When you try this lab, the **Books to Scrape** website might differ from what you expect.

If you encounter issues due to these changes, like new rules or obstacles preventing data extraction, don’t worry! Get creative.

You can choose another website that interests you and is suitable for scraping data. Options like Wikipedia, The New York Times, or even library databases are great alternatives. The main goal remains the same: extract useful data and enhance your web scraping skills while exploring a source of information you enjoy. This is your opportunity to practice and adapt to different web environments!

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
# Website we want to scrape

url = "https://books.toscrape.com/"
response = requests.get(url)

response.status_code

200

In [3]:
# Parse the HTML content

soup = BeautifulSoup(response.content, "html.parser")

In [5]:
# Check how many books are displayed

books = soup.find_all("article", class_="product_pod")

len(books)

20

In [6]:
# Select the first book on the page
book = books[0]

In [7]:
# Extract the book title
title = book.h3.a["title"]

title

'A Light in the Attic'

In [8]:
# Extract the book price
price = book.find("p", class_="price_color").text

price

'£51.77'

In [9]:
# Extract the book rating from the class attribute
rating = book.find("p", class_="star-rating")["class"]

rating

['star-rating', 'Three']

In [11]:
# Create a dictionary to convert text ratings into numbers
rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

In [12]:
# Convert the book rating into a number
rating_text = rating[1]
rating_number = rating_map[rating_text]

rating_number

3

In [13]:
# Extract the book availability
availability = book.find("p", class_="instock availability").text.strip()

availability

'In stock'

In [14]:
# Get the relative URL of the book
book_url = book.h3.a["href"]

book_url

'catalogue/a-light-in-the-attic_1000/index.html'

In [17]:
# Build the complete URL
full_url = "https://books.toscrape.com/" + book_url

In [18]:
# Request the book page
book_response = requests.get(full_url)

# Check that everything worked
book_response.status_code

200

In [19]:
# Parse the HTML of the book detail page
book_soup = BeautifulSoup(book_response.content, "html.parser")

In [21]:
# Extract the Universal Product Code (UPC)
upc = book_soup.find("table").find_all("td")[0].text

upc

'a897fe39b1053632'

In [22]:
# Extract the book genre from the breadcrumb navigation
genre = book_soup.find_all("a")[3].text

genre

'Poetry'

In [23]:
# Extract the product description
description = book_soup.find("meta", attrs={"name": "description"})["content"].strip()

description

"It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more"

In [26]:
# Create an empty list to store book information
books_data = []

# Loop through all books on the page
for book in books:

    # Extract the title
    title = book.h3.a["title"]

    # Extract and clean the price
    price = float(book.find("p", class_="price_color").text.replace("£", ""))

    # Extract and convert the rating
    rating_text = book.find("p", class_="star-rating")["class"][1]
    rating = rating_map[rating_text]

    # Extract availability
    availability = book.find("p", class_="instock availability").text.strip()

    # Build the detail page URL
    book_url = book.h3.a["href"]
    full_url = "https://books.toscrape.com/" + book_url

    # Request and parse the detail page
    detail_response = requests.get(full_url)
    detail_soup = BeautifulSoup(detail_response.content, "html.parser")

    # Extract UPC
    upc = detail_soup.find("table").find_all("td")[0].text

    # Extract genre
    genre = detail_soup.find_all("a")[3].text

    # Extract description
    description = detail_soup.find("meta", attrs={"name": "description"})["content"].strip()

    # Store all information
    books_data.append({
        "UPC": upc,
        "Title": title,
        "Price (£)": price,
        "Rating": rating,
        "Genre": genre,
        "Availability": availability,
        "Description": description
    })

In [27]:
len(books_data)

20

In [28]:
# Convert the list of dictionaries into a DataFrame
df_books = pd.DataFrame(books_data)

In [31]:

df_books.head()

,UPC,Title,Price (£),Rating,Genre,Availability,Description
0,a897fe39b1053632,A Light in the Attic,51.77,3,Poetry,In stock,It's hard to imagine a world without A Light i...
1,90fa61229261140a,Tipping the Velvet,53.74,1,Historical Fiction,In stock,"""Erotic and absorbing...Written with starling ..."
2,6957f44c3847a760,Soumission,50.10,1,Fiction,In stock,"Dans une France assez proche de la nôtre, un h..."
3,e00eb4fd7b871a48,Sharp Objects,47.82,4,Mystery,In stock,"WICKED above her hipbone, GIRL across her hear..."
4,4165285e1663650f,Sapiens: A Brief History of Humankind,54.23,5,History,In stock,From a renowned historian comes a groundbreaki...

In [32]:

df_books.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   UPC           20 non-null     str
 1   Title         20 non-null     str
 2   Price (£)     20 non-null     float64
 3   Rating        20 non-null     int64
 4   Genre         20 non-null     str
 5   Availability  20 non-null     str
 6   Description   20 non-null     str
dtypes: float64(1), int64(1), str(5)
memory usage: 1.2 KB

In [33]:
# Books rated 4 stars or more
df_books[df_books["Rating"] >= 4]

,UPC,Title,Price (£),Rating,Genre,Availability,Description
3,e00eb4fd7b871a48,Sharp Objects,47.82,4,Mystery,In stock,"WICKED above her hipbone, GIRL across her hear..."
4,4165285e1663650f,Sapiens: A Brief History of Humankind,54.23,5,History,In stock,From a renowned historian comes a groundbreaki...
6,2597b5a345f45e1b,The Dirty Little Secrets of Getting Your Dream...,33.34,4,Business,In stock,Drawing on his extensive experience evaluating...
8,e10e1e165dc8be4a,The Boys in the Boat: Nine Americans and Their...,22.60,4,Default,In stock,For readers of Laura Hillenbrand's Seabiscuit ...
11,30a7f60cd76ca58c,Shakespeare's Sonnets,20.66,4,Poetry,In stock,This book is an important and complete collect...
12,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock,Aaron Ledbetter’s future had been planned out ...
13,3b1c02bac2a429e6,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,5,Sequential Art,In stock,Scott Pilgrim's life is totally sweet. He's 23...
14,a34ba96d4081e6a4,Rip it Up and Start Again,35.02,5,Music,In stock,"Punk's raw power rejuvenated rock, but by the ..."

In [34]:
# Books rated 4 stars or more and costing £20 or less
df_books[
    (df_books["Rating"] >= 4) &
    (df_books["Price (£)"] <= 20)
]

,UPC,Title,Price (£),Rating,Genre,Availability,Description
12,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock,Aaron Ledbetter’s future had been planned out ...

In [35]:
def scrape_books(min_rating, max_price):
    # Website page to scrape
    url = "https://books.toscrape.com/"
    
    # Send request and parse HTML
    response = requests.get(url)
    soup = BeautifulSoup(response.content, "html.parser")
    
    # Find all book containers
    books = soup.find_all("article", class_="product_pod")
    
    # Dictionary to convert text ratings into numbers
    rating_map = {
        "One": 1,
        "Two": 2,
        "Three": 3,
        "Four": 4,
        "Five": 5
    }
    
    # Store scraped data
    books_data = []
    
    # Loop through all books on the page
    for book in books:
        title = book.h3.a["title"]
        price = float(book.find("p", class_="price_color").text.replace("£", ""))
        
        rating_text = book.find("p", class_="star-rating")["class"][1]
        rating = rating_map[rating_text]
        
        availability = book.find("p", class_="instock availability").text.strip()
        
        book_url = book.h3.a["href"]
        full_url = "https://books.toscrape.com/" + book_url
        
        detail_response = requests.get(full_url)
        detail_soup = BeautifulSoup(detail_response.content, "html.parser")
        
        upc = detail_soup.find("table").find_all("td")[0].text
        genre = detail_soup.find_all("a")[3].text
        description = detail_soup.find("meta", attrs={"name": "description"})["content"].strip()
        
        # Apply filters
        if rating >= min_rating and price <= max_price:
            books_data.append({
                "UPC": upc,
                "Title": title,
                "Price (£)": price,
                "Rating": rating,
                "Genre": genre,
                "Availability": availability,
                "Description": description
            })
    
    # Return results as a DataFrame
    return pd.DataFrame(books_data)

In [36]:
filtered_books = scrape_books(min_rating=4, max_price=20)

filtered_books

,UPC,Title,Price (£),Rating,Genre,Availability,Description
0,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock,Aaron Ledbetter’s future had been planned out ...